version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      # Check for npm updates on Sundays
      day: 'sunday'
    ignore:
      - dependency-name: 'react'
        versions: ['18.x']
      - dependency-name: 'react-dom'
        versions: ['18.x']
      - dependency-name: '@types/react'
        versions: ['18.x']
      - dependency-name: '@types/react-dom'
        versions: ['18.x']
